
#
# Config.
#

url: http://blog.datasommelier.com
writeKey: GoKlsjKAo3qj1YDUNsB3Co69yWUZMIUC

#
# Bio.
#

name: Becky Jaimes
role: Data Sommelier

#
# Social.
#

twitter: 
github: TheBecky
email: becky@datasommelier.com
